project:
  type: book

resources: 
  - data/*

book:
  title: "Computational Workflows for Engineers"
  reader-mode: true

  page-footer:
    left: "© 2026 Ozan Ozbeker | CC-BY-NC-ND 4.0"
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://ozanozbeker.com/cw4e/
  repo-url: https://github.com/ozanozbeker/cw4e/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - introduction.qmd
    - prerequisites.qmd

    - part: foundations/index.qmd
      chapters:
        - foundations/computers.qmd
        - foundations/files.qmd
        - foundations/cli.qmd
        - foundations/git.qmd
        - foundations/github.qmd
    - part: databases/index.qmd
      chapters:
        - databases/databases.qmd
        - databases/querying.qmd
        - databases/joins.qmd
        - databases/analytics.qmd
        - databases/modeling.qmd
    # - part: 03_programming/index.qmd
    # - part: 04_integration/index.qmd
    # - part: 05_delivery/index.qmd

    # - references.qmd

  appendices:
    # - appendices/basedpyright.qmd
    - appendices/brew.qmd
    # - appendices/duckdb.qmd
    - appendices/git.qmd
    - appendices/github.qmd
    # - appendices/marimo.qmd
    # - appendices/uv.qmd
    # - appendices/ruff.qmd
    - appendices/winget.qmd
    - appendices/zed.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles.scss
    author-meta: "Ozan Ozbeker"
    callout-appearance: "simple"
    highlight-style: nord

editor: source
