project:
  type: book
  post-render: ./post-render.sh

resources:
  - data/*
  - images/*

book:
  title: "Computational Workflows for Engineers"
  reader-mode: true

  page-footer:
    left: "© 2026 Ozan Ozbeker | CC-BY-NC-ND 4.0"
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://ozanozbeker.com/cw4e/
  repo-url: https://github.com/ozanozbeker/cw4e/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - introduction.qmd
    - prerequisites.qmd

    - part: unit-1-toolkit.qmd
      chapters:
        - chapters/01-computers.qmd
        - chapters/02-filesystem.qmd
        - chapters/03-quarto.qmd
        - chapters/04-cli.qmd
        - chapters/05-git.qmd
        - chapters/06-github.qmd
    - part: unit-2-sql.qmd
      chapters:
        - chapters/07-databases.qmd
        - chapters/08-querying.qmd
        - chapters/09-joins.qmd
        - chapters/10-analytics.qmd
        - chapters/11-modeling.qmd
    - part: unit-3-python.qmd
      chapters:
        - chapters/12-python-fundamentals.qmd
        - chapters/13-collections.qmd
        - chapters/14-control-flow.qmd
        - chapters/15-functions.qmd
        - chapters/16-file-io.qmd
        - chapters/17-objects.qmd
    - part: unit-4-data-products.qmd
      chapters:
        - chapters/18-python-sql.qmd
        - chapters/19-polars.qmd
        - chapters/20-altair.qmd
        - chapters/21-excel.qmd
        - chapters/22-python-projects.qmd
        - chapters/23-code-quality.qmd
        - chapters/24-computational-documents.qmd
        - chapters/25-arrow.qmd
        - chapters/26-typer.qmd

  appendices:
    - appendices/brew.qmd
    - appendices/winget.qmd
    - appendices/zed.qmd
    - appendices/git.qmd
    - appendices/github.qmd
    - appendices/northwind.qmd
    - appendices/duckdb.qmd
    - appendices/uv.qmd
    - appendices/marimo.qmd
    - appendices/ruff.qmd
    - appendices/basedpyright.qmd

execute:
  enabled: false

format:
  html:
    theme:
      - litera
      - custom.scss
    author-meta: "Ozan Ozbeker"
    callout-appearance: "simple"
    highlight-style: nord
    other-links:
      - text: SQL & Python Playground
        icon: play-circle
        href: https://ozanozbeker.com/cw4e/playground/

editor: source
