# Databases {.unnumbered}

In the Foundations module, you learned to navigate your computer like an engineer: managing files from the command line, tracking changes with Git, and collaborating through GitHub. Those skills gave you the infrastructure to work reliably. Now we need something to work *on*.

This module introduces databases, the structured systems that store and organize the data you'll spend your career analyzing. More importantly, it introduces SQL (Structured Query Language), the language that lets you ask questions of that data. SQL is one of the most enduring and widely-used languages in computing, and for good reason: it lets you express complex analytical questions in a few lines of declarative logic, then lets the database figure out the fastest way to answer them.

We'll use DuckDB throughout this module, an analytical database that installs in seconds and runs entirely on your laptop. You won't need to configure servers, manage permissions, or request access from an IT department. By the end of the first chapter, you'll be writing real queries against real data.

The module progresses through five chapters. You start by understanding what databases are, where they fit alongside spreadsheets, and why different kinds exist. Then you learn to query single tables and combine results with set operations. Next you bring multiple tables together through joins, then graduate to advanced analytical patterns like window functions, CTEs, and ABC classification. The final chapter flips the perspective: instead of querying existing databases, you'll design and build your own, learning about normalization, dimensional modeling, ER diagrams, and the documentation practices that make databases usable.

Throughout, we'll work with the Northwind database, a classic dataset representing a food import and export company called Northwind Traders. It has suppliers, products, customers, orders, and shippers, which makes it a natural fit for thinking about supply chain and operations problems. Every chapter opens with a business question that creates genuine need for the SQL concepts being introduced, because SQL is a tool for answering questions, not an abstract syntax to memorize.

The SQL you learn here is standard SQL, the core that works across PostgreSQL, MySQL, SQL Server, Oracle, and every other major relational database. When we use DuckDB-specific convenience features, we'll call them out clearly and show the portable alternative. You're learning a skill that transfers to whatever database you encounter next.

A note on how to learn SQL effectively: don't just read the examples. For every query you encounter in this book, predict what you think the output will look like before you run it. When the result surprises you, stop and figure out why. Try modifying the query, break it on purpose, then fix it. SQL rewards experimentation, and the DuckDB UI gives you instant feedback with no risk of damaging anything. The goal isn't to memorize syntax; it's to build intuition for how data flows through a query so you can think and act flexibly when facing new problems.
