<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ozan Ozbeker">

<title>10&nbsp; Data Modeling – Computational Workflows for Engineers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../programming.html" rel="next">
<link href="../chapters/09-analytics.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-aa0bfeffdde32bb1c7607de7a91446fc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b6eb9a42dae6f26db387f79c752c72c8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../databases.html">Databases</a></li><li class="breadcrumb-item"><a href="../chapters/10-modeling.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Modeling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Computational Workflows for Engineers</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ozanozbeker/cw4e/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prerequisites.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prerequisites</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-computers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Computer Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-filesystem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Files and the File System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Command Line</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Version Control with Git</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-github.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Collaboration with GitHub</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../databases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Databases</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-databases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Databases</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-querying.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Querying Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-joins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Joining Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analytical SQL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-modeling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Modeling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-python-fundamentals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Python Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-collections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Collections &amp; Control Flow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Functions &amp; Modules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-file-io.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Working with Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Objects &amp; Type Hints</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Integration</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-python-sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Python Meets SQL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-marimo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Notebooks with Marimo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-polars.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">DataFrames with Polars</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-altair.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Data Visualization with Altair</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-excel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Working with Excel</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Production</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-python-projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Python Projects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Documents &amp; Presentations with Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-code-quality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Code Quality: Ruff, basedpyright, &amp; Language Servers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/24-arrow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Arrow, ADBC, &amp; Database Connectivity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/25-typer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">CLI Tools with Typer</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/brew.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Homebrew</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/winget.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">WinGet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/zed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Zed</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Git Configuration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/github.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">GitHub Configuration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/northwind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Northwind Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/duckdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">DuckDB</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/uv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">uv</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/marimo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Marimo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/ruff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Ruff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/basedpyright.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">basedpyright</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#thinking-in-entities-and-relationships" id="toc-thinking-in-entities-and-relationships" class="nav-link active" data-scroll-target="#thinking-in-entities-and-relationships"><span class="header-section-number">10.1</span> Thinking in Entities and Relationships</a>
  <ul class="collapse">
  <li><a href="#drawing-er-diagrams-with-dbdiagram.io" id="toc-drawing-er-diagrams-with-dbdiagram.io" class="nav-link" data-scroll-target="#drawing-er-diagrams-with-dbdiagram.io"><span class="header-section-number">10.1.1</span> Drawing ER Diagrams with dbdiagram.io</a></li>
  <li><a href="#crows-foot-notation" id="toc-crows-foot-notation" class="nav-link" data-scroll-target="#crows-foot-notation"><span class="header-section-number">10.1.2</span> Crow’s Foot Notation</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">10.1.3</span> Exercises</a></li>
  </ul></li>
  <li><a href="#create-table-turning-design-into-structure" id="toc-create-table-turning-design-into-structure" class="nav-link" data-scroll-target="#create-table-turning-design-into-structure"><span class="header-section-number">10.2</span> CREATE TABLE: Turning Design into Structure</a>
  <ul class="collapse">
  <li><a href="#data-types" id="toc-data-types" class="nav-link" data-scroll-target="#data-types"><span class="header-section-number">10.2.1</span> Data Types</a></li>
  <li><a href="#constraints-rules-the-database-enforces" id="toc-constraints-rules-the-database-enforces" class="nav-link" data-scroll-target="#constraints-rules-the-database-enforces"><span class="header-section-number">10.2.2</span> Constraints: Rules the Database Enforces</a></li>
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"><span class="header-section-number">10.2.3</span> Exercises</a></li>
  </ul></li>
  <li><a href="#why-tables-are-split-normalization" id="toc-why-tables-are-split-normalization" class="nav-link" data-scroll-target="#why-tables-are-split-normalization"><span class="header-section-number">10.3</span> Why Tables Are Split: Normalization</a>
  <ul class="collapse">
  <li><a href="#how-much-normalization" id="toc-how-much-normalization" class="nav-link" data-scroll-target="#how-much-normalization"><span class="header-section-number">10.3.1</span> How Much Normalization?</a></li>
  </ul></li>
  <li><a href="#dimensional-modeling-how-analytical-databases-are-designed" id="toc-dimensional-modeling-how-analytical-databases-are-designed" class="nav-link" data-scroll-target="#dimensional-modeling-how-analytical-databases-are-designed"><span class="header-section-number">10.4</span> Dimensional Modeling: How Analytical Databases Are Designed</a>
  <ul class="collapse">
  <li><a href="#fact-tables-the-measurements" id="toc-fact-tables-the-measurements" class="nav-link" data-scroll-target="#fact-tables-the-measurements"><span class="header-section-number">10.4.1</span> Fact Tables: The Measurements</a></li>
  <li><a href="#dimension-tables-the-context" id="toc-dimension-tables-the-context" class="nav-link" data-scroll-target="#dimension-tables-the-context"><span class="header-section-number">10.4.2</span> Dimension Tables: The Context</a></li>
  <li><a href="#star-schema" id="toc-star-schema" class="nav-link" data-scroll-target="#star-schema"><span class="header-section-number">10.4.3</span> Star Schema</a></li>
  <li><a href="#exercises-2" id="toc-exercises-2" class="nav-link" data-scroll-target="#exercises-2"><span class="header-section-number">10.4.4</span> Exercises</a></li>
  </ul></li>
  <li><a href="#views-saved-queries" id="toc-views-saved-queries" class="nav-link" data-scroll-target="#views-saved-queries"><span class="header-section-number">10.5</span> Views: Saved Queries</a></li>
  <li><a href="#documenting-your-data-the-catalog-mindset" id="toc-documenting-your-data-the-catalog-mindset" class="nav-link" data-scroll-target="#documenting-your-data-the-catalog-mindset"><span class="header-section-number">10.6</span> Documenting Your Data: The Catalog Mindset</a></li>
  <li><a href="#manipulating-data-insert-update-delete" id="toc-manipulating-data-insert-update-delete" class="nav-link" data-scroll-target="#manipulating-data-insert-update-delete"><span class="header-section-number">10.7</span> Manipulating Data: INSERT, UPDATE, DELETE</a>
  <ul class="collapse">
  <li><a href="#insert-adding-rows" id="toc-insert-adding-rows" class="nav-link" data-scroll-target="#insert-adding-rows"><span class="header-section-number">10.7.1</span> INSERT: Adding Rows</a></li>
  <li><a href="#insert-from-a-query" id="toc-insert-from-a-query" class="nav-link" data-scroll-target="#insert-from-a-query"><span class="header-section-number">10.7.2</span> INSERT from a Query</a></li>
  <li><a href="#update-modifying-existing-rows" id="toc-update-modifying-existing-rows" class="nav-link" data-scroll-target="#update-modifying-existing-rows"><span class="header-section-number">10.7.3</span> UPDATE: Modifying Existing Rows</a></li>
  <li><a href="#delete-removing-rows" id="toc-delete-removing-rows" class="nav-link" data-scroll-target="#delete-removing-rows"><span class="header-section-number">10.7.4</span> DELETE: Removing Rows</a></li>
  <li><a href="#exercises-3" id="toc-exercises-3" class="nav-link" data-scroll-target="#exercises-3"><span class="header-section-number">10.7.5</span> Exercises</a></li>
  </ul></li>
  <li><a href="#working-with-real-world-data" id="toc-working-with-real-world-data" class="nav-link" data-scroll-target="#working-with-real-world-data"><span class="header-section-number">10.8</span> Working with Real-World Data</a></li>
  <li><a href="#chapter-exercises" id="toc-chapter-exercises" class="nav-link" data-scroll-target="#chapter-exercises"><span class="header-section-number">10.9</span> Chapter Exercises</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">10.10</span> Summary</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="header-section-number">10.11</span> Glossary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ozanozbeker/cw4e/edit/main/chapters/10-modeling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ozanozbeker/cw4e/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div><div class="quarto-other-links"><h2>Other Links</h2><ul><li><a href="playground/index.html"><i class="bi bi-play-circle"></i>SQL &amp; Python Playground</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../databases.html">Databases</a></li><li class="breadcrumb-item"><a href="../chapters/10-modeling.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Modeling</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-modeling" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data Modeling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Every chapter until now has put you in the role of analyst: someone who queries existing databases to answer questions. But someone had to design those databases. Someone decided that products and suppliers should be separate tables, that <code>supplier_id</code> should link them, that <code>unit_price</code> should be a decimal and not a string. Those design decisions shape every query you’ll ever write against that data, and bad design decisions create problems that no amount of clever SQL can fix.</p>
<p>This chapter flips your perspective from consumer to creator. You’ll learn to design schemas that organize data logically, create tables with appropriate data types and constraints, understand why tables are structured the way they are, and build views that simplify complex queries for others. You’ll also learn the basic data manipulation operations, <code>INSERT</code>, <code>UPDATE</code>, and <code>DELETE</code>, that populate and maintain the tables you create. By the end, you’ll be able to look at a business process and translate it into a database schema that stores the data correctly and makes analytical queries natural.</p>
<section id="thinking-in-entities-and-relationships" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="thinking-in-entities-and-relationships"><span class="header-section-number">10.1</span> Thinking in Entities and Relationships</h2>
<p>Before writing any SQL, database design starts with identifying the <strong>entities</strong> and <strong>relationships</strong> in your domain. An entity is a distinct thing you need to track: a product, a customer, an order, a machine, a sensor reading. A relationship describes how entities connect: a customer <em>places</em> orders, an order <em>contains</em> products, a supplier <em>provides</em> products.</p>
<p>Consider a quality control process on a manufacturing floor. The entities might include production lines (where products are made), inspection events (when someone checks a batch), defect records (individual problems found), and operators (the people running the lines). The relationships: a production line <em>hosts</em> many inspection events, each inspection event <em>may find</em> multiple defects, and an operator <em>conducts</em> each inspection.</p>
<p>Sketching this out, even informally on paper or a whiteboard, before touching SQL is one of the most valuable habits in data work. The sketch is called an <strong>entity-relationship diagram</strong> (ERD), and even a rough one prevents the most expensive design mistakes.</p>
<p>The process follows three steps:</p>
<ol type="1">
<li>Identify the nouns in your domain. These are candidate entities, each likely becoming a table.</li>
<li>Identify the verbs connecting those nouns. These are relationships, each likely becoming a foreign key.</li>
<li>Identify the attributes of each entity. These become the columns in each table.</li>
</ol>
<p>For the manufacturing quality control example, that sketch might look like:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>output</strong></pre>
</div>
<pre class="text" data-filename="output"><code>production_lines: line_id, line_name, building, capacity
operators: operator_id, name, shift, certification_level
inspections: inspection_id, line_id, operator_id, inspection_date, batch_size
defects: defect_id, inspection_id, defect_type, severity, description</code></pre>
</div>
<p>Each entity has a primary key (<code>line_id</code>, <code>operator_id</code>, etc.), and relationships are expressed through foreign keys (<code>line_id</code> in <code>inspections</code> references <code>production_lines</code>, <code>inspection_id</code> in <code>defects</code> references <code>inspections</code>).</p>
<section id="drawing-er-diagrams-with-dbdiagram.io" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="drawing-er-diagrams-with-dbdiagram.io"><span class="header-section-number">10.1.1</span> Drawing ER Diagrams with dbdiagram.io</h3>
<p>While hand-drawn sketches work for initial brainstorming, a proper tool makes ER diagrams shareable, version-controllable, and translatable to SQL. <strong>dbdiagram.io</strong> is a free web-based tool that uses a code-to-diagram approach: you type a schema definition in a simple markup language called <strong>DBML</strong> (Database Markup Language) on the left panel, and the diagram auto-generates on the right.</p>
<p>Here’s the quality control schema in DBML:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>dbdiagram.io</strong></pre>
</div>
<pre class="dbml" data-filename="dbdiagram.io"><code>Table production_lines {
  line_id integer [pk]
  line_name varchar [not null, unique]
  building varchar [not null]
  capacity integer
}

Table operators {
  operator_id integer [pk]
  name varchar [not null]
  shift varchar [not null]
  cert_level integer
}

Table inspections {
  inspection_id integer [pk]
  line_id integer [not null, ref: &gt; production_lines.line_id]
  operator_id integer [not null, ref: &gt; operators.operator_id]
  inspection_date date [not null]
  batch_size integer [not null]
}

Table defects {
  defect_id integer [pk]
  inspection_id integer [not null, ref: &gt; inspections.inspection_id]
  defect_type varchar [not null]
  severity integer [not null]
  description varchar
}</code></pre>
</div>
<p>The <code>ref: &gt;</code> syntax defines a foreign key relationship (many-to-one, where the arrow points toward the “one” side). Column settings like <code>pk</code>, <code>not null</code>, <code>unique</code>, and <code>ref</code> map directly to the SQL constraints you’ll learn in this chapter. The free tier gives you unlimited personal diagrams and can export to PNG, PDF, or SQL for PostgreSQL, MySQL, SQL Server, and Oracle.</p>
<p>The code-based approach has an important advantage for engineers: your schema definition is text, which means it can be tracked in Git alongside the rest of your project. The diagram becomes a living document that evolves with your database.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Naming Conventions Matter More Than You Think
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pick a naming convention and enforce it ruthlessly: <code>snake_case</code> or <code>camelCase</code> for columns, singular or plural table names, whether IDs are <code>id</code>, <code>product_id</code>, or <code>productID</code>. It seems trivial until you inherit a database where every table uses a different convention and you can’t remember whether the column is <code>customerId</code>, <code>customer_id</code>, or <code>cust_id</code>. The Northwind database uses <code>snake_case</code> (e.g., <code>unit_price</code>, <code>company_name</code>), which is the convention preferred by most modern data teams because it’s easier to read. You’ll also encounter <code>camelCase</code> (<code>unitPrice</code>, <code>companyName</code>) in Microsoft ecosystems and older databases. Whatever you choose, consistency is more important than the choice itself.</p>
</div>
</div>
</section>
<section id="crows-foot-notation" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="crows-foot-notation"><span class="header-section-number">10.1.2</span> Crow’s Foot Notation</h3>
<p>ER diagram tools use a visual language called <strong>Crow’s foot notation</strong> to represent relationship types. The symbols at the end of each relationship line tell you two things: whether the relationship is mandatory or optional, and whether it connects to one entity or many.</p>
<p>Three symbols combine to express any relationship. A <strong>vertical bar</strong> (|) means “exactly one” or “mandatory.” A <strong>circle</strong> (○) means “zero” or “optional.” A <strong>crow’s foot</strong> (the forked symbol that looks like a bird’s foot) means “many.”</p>
<p>Reading a relationship between two tables, you look at the symbols on each end:</p>
<p><code>||──||</code> means one and only one on both sides (one-to-one, both mandatory). <code>||──○&lt;</code> means one on the left (mandatory), zero or many on the right (the crow’s foot with a circle). This is the classic one-to-many relationship: one production line has zero or many inspections, but each inspection belongs to exactly one production line.</p>
<p>When you see a crow’s foot on both ends (<code>○&lt;──&gt;○</code>), that signals a many-to-many relationship, which requires a junction table to implement (as you learned with <code>order_details</code> in the joins chapter).</p>
<p>You don’t need to memorize every combination. The key insight is learning to read these diagrams so you can navigate unfamiliar schemas, because in professional work, you’ll encounter ER diagrams long before you encounter the actual data.</p>
</section>
<section id="exercises" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="exercises"><span class="header-section-number">10.1.3</span> Exercises</h3>
<ol type="1">
<li><p>A university needs to track students, courses, and enrollments. Each student can enroll in many courses, and each course has many students. Sketch the entities, relationships, and key columns (on paper or in text). What type of relationship exists between students and courses, and what table do you need to resolve it?</p></li>
<li><p>For the Northwind database, identify the relationship type (one-to-one, one-to-many, or many-to-many) between: (a) <code>suppliers</code> and <code>products</code>, (b) <code>orders</code> and <code>order_details</code>, (c) <code>orders</code> and <code>products</code>. For each many-to-many relationship, name the junction table.</p></li>
<li><p>Open dbdiagram.io and enter the quality control DBML example from this chapter. Examine the generated diagram. Then add a new table called <code>corrective_actions</code> that tracks fixes applied after defects are found. Each corrective action references a specific defect. What does the DBML look like?</p></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> Many-to-many between students and courses. Junction table <strong>enrollments</strong>: enrollmentID (PK), studentID (FK), courseID (FK), grade, enrollmentDate.</p>
<p><strong>2.</strong> (a) suppliers→products: one-to-many. (b) orders→order_details: one-to-many. (c) orders→products: many-to-many, junction table = order_details.</p>
<p><strong>3.</strong> DBML for corrective_actions: <code>Table corrective_actions { action_id integer [pk]  defect_id integer [not null, ref: &gt; defects.defect_id]  action_description varchar [not null]  completion_date date  cost decimal }</code></p>
</div>
</div>
</div>
</section>
</section>
<section id="create-table-turning-design-into-structure" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="create-table-turning-design-into-structure"><span class="header-section-number">10.2</span> CREATE TABLE: Turning Design into Structure</h2>
<p>The <code>CREATE TABLE</code> statement defines a table’s structure: its name, its columns, and the rules those columns must follow.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> production_lines (</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    line_id     <span class="dt">INTEGER</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    line_name   <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    building    <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    capacity    <span class="dt">INTEGER</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Each column declaration has three parts: the <strong>name</strong>, the <strong>data type</strong>, and optional <strong>constraints</strong> that enforce rules about what values are allowed.</p>
<section id="data-types" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="data-types"><span class="header-section-number">10.2.1</span> Data Types</h3>
<p>Choosing the right data type prevents entire categories of data quality problems. If a column stores prices and you define it as <code>VARCHAR</code>, nothing stops someone from inserting “N/A” or “TBD” where a number should be. If you define it as <code>DECIMAL(10, 2)</code>, the database rejects anything that isn’t a valid number with up to two decimal places.</p>
<p>The essential data types you’ll use regularly:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>What It Stores</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>INTEGER</code></td>
<td>Whole numbers</td>
<td>IDs, counts, quantities</td>
</tr>
<tr class="even">
<td><code>DECIMAL(p, s)</code></td>
<td>Exact decimal numbers with precision <code>p</code> and scale <code>s</code></td>
<td>Prices, measurements</td>
</tr>
<tr class="odd">
<td><code>DOUBLE</code></td>
<td>Approximate floating-point numbers</td>
<td>Scientific data, calculations</td>
</tr>
<tr class="even">
<td><code>VARCHAR</code></td>
<td>Variable-length text</td>
<td>Names, descriptions, codes</td>
</tr>
<tr class="odd">
<td><code>DATE</code></td>
<td>Calendar dates</td>
<td><code>2024-03-15</code></td>
</tr>
<tr class="even">
<td><code>TIMESTAMP</code></td>
<td>Date and time</td>
<td><code>2024-03-15 14:30:00</code></td>
</tr>
<tr class="odd">
<td><code>BOOLEAN</code></td>
<td>True or false</td>
<td>Flags, yes/no fields</td>
</tr>
</tbody>
</table>
<p>A few type choices deserve special attention.</p>
<p>Use <code>DECIMAL</code> for money, never <code>DOUBLE</code>. Floating-point arithmetic introduces rounding errors that accumulate in financial calculations. <code>DECIMAL(10, 2)</code> stores values like <code>1234567.89</code> exactly as specified. You may have noticed that older versions of the Northwind database stored <code>unit_price</code> as <code>DOUBLE</code>. This is a common shortcut in sample datasets, but in a production system handling real financial data, you’d define it as <code>DECIMAL(10, 2)</code> to guarantee exact arithmetic.</p>
<p>Use <code>VARCHAR</code> without a length limit in DuckDB. Unlike older databases that required you to declare <code>VARCHAR(255)</code>, DuckDB handles variable-length strings efficiently without an arbitrary cap.</p>
<p>Use <code>DATE</code> for dates and <code>TIMESTAMP</code> for dates with times. Storing dates as strings (<code>"03/15/2024"</code>) prevents you from using date functions, makes sorting unreliable, and opens the door to format inconsistencies.</p>
</section>
<section id="constraints-rules-the-database-enforces" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="constraints-rules-the-database-enforces"><span class="header-section-number">10.2.2</span> Constraints: Rules the Database Enforces</h3>
<p>Constraints are the guardrails that keep your data clean. They define what values are acceptable, and the database rejects any operation that would violate them.</p>
<p><strong>PRIMARY KEY</strong> uniquely identifies each row. No duplicates, no <code>NULL</code> values. Every table should have one.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> operators (</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    operator_id <span class="dt">INTEGER</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    name        <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    shift       <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    cert_level  <span class="dt">INTEGER</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>NOT NULL</strong> prevents missing values in a column. Use this for any column that must always have data. An operator must always have a name and shift, so those are <code>NOT NULL</code>. The certification level might not yet be recorded for new hires, so it allows <code>NULL</code>.</p>
<p><strong>FOREIGN KEY</strong> enforces referential integrity: it guarantees that a reference to another table actually points to an existing row.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> inspections (</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    inspection_id   <span class="dt">INTEGER</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    line_id         <span class="dt">INTEGER</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> production_lines(line_id),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    operator_id     <span class="dt">INTEGER</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> operators(operator_id),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    inspection_date <span class="dt">DATE</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    batch_size      <span class="dt">INTEGER</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>REFERENCES</code> clause says “the value in <code>line_id</code> must exist in <code>production_lines.line_id</code>.” If you try to insert an inspection for a production line that doesn’t exist, the database rejects it. This prevents <strong>orphaned records</strong>, rows that reference nonexistent entities.</p>
<p><strong>UNIQUE</strong> ensures no two rows share the same value in a column (or combination of columns), separate from the primary key. You might require that each production line has a unique name:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> production_lines (</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    line_id   <span class="dt">INTEGER</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    line_name <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">UNIQUE</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    building  <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    capacity  <span class="dt">INTEGER</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>CHECK</strong> enforces a custom condition:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> defects (</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    defect_id     <span class="dt">INTEGER</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    inspection_id <span class="dt">INTEGER</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> inspections(inspection_id),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    defect_type   <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    severity      <span class="dt">INTEGER</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">CHECK</span> (severity <span class="kw">BETWEEN</span> <span class="dv">1</span> <span class="kw">AND</span> <span class="dv">5</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    description   <span class="dt">VARCHAR</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>CHECK</code> constraint guarantees that severity is always between 1 and 5. Inserting a severity of 0 or 6 fails immediately, rather than silently corrupting your data and surfacing as a mysterious bug weeks later.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>DuckDB’s Constraint Support
</div>
</div>
<div class="callout-body-container callout-body">
<p>DuckDB supports <code>PRIMARY KEY</code>, <code>NOT NULL</code>, <code>UNIQUE</code>, and <code>CHECK</code> constraints and enforces them. DuckDB also accepts <code>FOREIGN KEY</code> syntax, but as of current versions, foreign key constraints are parsed but not fully enforced at the data level. This means DuckDB won’t reject an insert with an invalid foreign key reference. The syntax is still valuable for documenting relationships and for writing portable SQL that works in PostgreSQL or other databases where foreign keys are enforced.</p>
</div>
</div>
</section>
<section id="exercises-1" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="exercises-1"><span class="header-section-number">10.2.3</span> Exercises</h3>
<ol type="1">
<li><p>Write a <code>CREATE TABLE</code> statement for a <code>machines</code> table in a manufacturing context. It should have a machine ID (primary key), machine name (unique, required), installation date (required), and a maintenance cost per hour that must be positive. Choose appropriate data types for each column.</p></li>
<li><p>What constraint would you add to prevent someone from inserting an inspection with a <code>batch_size</code> of zero or negative? Write the column definition.</p></li>
<li><p>Predict what happens when you run each of these statements against the quality control schema, and explain why:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Statement A</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> operators (operator_id, name, shift, cert_level)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">VALUES</span> (<span class="dv">1</span>, <span class="kw">NULL</span>, <span class="st">'Morning'</span>, <span class="dv">3</span>);</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">-- Statement B</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> defects (defect_id, inspection_id, defect_type, severity, description)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="kw">VALUES</span> (<span class="dv">1</span>, <span class="dv">999</span>, <span class="st">'Scratch'</span>, <span class="dv">3</span>, <span class="st">'Minor surface scratch'</span>);</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co">-- Statement C</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> defects (defect_id, inspection_id, defect_type, severity, description)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="kw">VALUES</span> (<span class="dv">2</span>, <span class="dv">1</span>, <span class="st">'Crack'</span>, <span class="dv">7</span>, <span class="st">'Structural crack in housing'</span>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div></li>
<li><p>Why does the text recommend using <code>DECIMAL(10, 2)</code> instead of <code>DOUBLE</code> for monetary values? What kind of error could <code>DOUBLE</code> introduce in a financial report?</p></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> machines (</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    machine_id <span class="dt">INTEGER</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    machine_name <span class="dt">VARCHAR</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">UNIQUE</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    installation_date <span class="dt">DATE</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    maintenance_cost_per_hour <span class="dt">DECIMAL</span>(<span class="dv">10</span>, <span class="dv">2</span>) <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">CHECK</span> (maintenance_cost_per_hour <span class="op">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>2.</strong> <code>batch_size INTEGER NOT NULL CHECK (batch_size &gt; 0)</code></p>
<p><strong>3.</strong> Statement A: FAILS,NOT NULL constraint on <code>name</code> rejects NULL. Statement B: In DuckDB, accepted (FK not enforced); in PostgreSQL, would fail because inspection_id 999 doesn’t exist. Statement C: FAILS,CHECK constraint rejects severity = 7 (must be BETWEEN 1 AND 5).</p>
<p><strong>4.</strong> DOUBLE uses floating-point arithmetic with inherent rounding errors. <code>0.1 + 0.2 = 0.30000000000000004</code> in floating-point. Over thousands of financial transactions, these errors accumulate and create unexplained discrepancies. DECIMAL stores values exactly.</p>
</div>
</div>
</div>
</section>
</section>
<section id="why-tables-are-split-normalization" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="why-tables-are-split-normalization"><span class="header-section-number">10.3</span> Why Tables Are Split: Normalization</h2>
<p>You already understand <em>that</em> data is split across tables (from the joins chapter), but understanding <em>why</em>, at a deeper level, prevents you from making poor design decisions in your own work.</p>
<p><strong>Normalization</strong> is the process of organizing a database to reduce redundancy and prevent inconsistencies. The formal theory involves “normal forms” (1NF, 2NF, 3NF, and beyond), but the practical intuition is simpler: <strong>each fact should live in exactly one place</strong>.</p>
<p>Consider this badly-designed table:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>output</strong></pre>
</div>
<pre class="text" data-filename="output"><code>orders_flat:
| order_id | customer_name | customer_address    | product_name | supplier_name | quantity |
|----------|---------------|---------------------|--------------|---------------|----------|
| 1001     | Acme Corp     | 123 Main St, NYC    | Widget A     | Parts Inc     | 50       |
| 1001     | Acme Corp     | 123 Main St, NYC    | Gadget B     | Tools Ltd     | 20       |
| 1002     | Acme Corp     | 123 Main St, NYC    | Widget A     | Parts Inc     | 30       |
| 1003     | Beta LLC      | 456 Oak Ave, Boston | Widget A     | Parts Inc     | 75       |</code></pre>
</div>
<p>Three problems are immediately visible.</p>
<p><strong>Redundancy</strong>: “Acme Corp” and “123 Main St, NYC” are stored three times. “Widget A” and “Parts Inc” are stored three times. This wastes storage, but more importantly, it creates the next two problems.</p>
<p><strong>Update anomaly</strong>: If Acme Corp moves to a new address, you must update every row that mentions them. Miss one, and the database now says Acme Corp is at two different addresses. Which one is right?</p>
<p><strong>Delete anomaly</strong>: If you delete order 1003 (the only order from Beta LLC), you lose the fact that Beta LLC exists and their address. The customer information disappears because it was entangled with the order data.</p>
<p>Normalization solves this by splitting into separate tables:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>output</strong></pre>
</div>
<pre class="text" data-filename="output"><code>customers: customer_id, customer_name, customer_address
products:  product_id, product_name, supplier_id
suppliers: supplier_id, supplier_name
orders:    order_id, customer_id
order_details: order_id, product_id, quantity</code></pre>
</div>
<p>Now each fact lives once. Updating Acme Corp’s address changes one row. Deleting an order doesn’t destroy customer data. Adding a new customer doesn’t require an order to exist.</p>
<section id="how-much-normalization" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="how-much-normalization"><span class="header-section-number">10.3.1</span> How Much Normalization?</h3>
<p>Normalization is a spectrum, not an absolute rule. Analytical databases, the kind you’ll work with most, often <strong>denormalize</strong> intentionally, tolerating some redundancy to avoid complex joins in frequent queries.</p>
<p>The practical guidance: normalize your source tables (where data enters the system) to prevent anomalies, and consider strategic denormalization in analytical tables (where data is queried heavily) to simplify queries.</p>
</section>
</section>
<section id="dimensional-modeling-how-analytical-databases-are-designed" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="dimensional-modeling-how-analytical-databases-are-designed"><span class="header-section-number">10.4</span> Dimensional Modeling: How Analytical Databases Are Designed</h2>
<p>While normalization is the right approach for operational systems that store and update data, analytical systems that primarily <em>read</em> data use a different design philosophy. <strong>Dimensional modeling</strong>, pioneered by Ralph Kimball, organizes analytical databases around two types of tables: <strong>fact tables</strong> and <strong>dimension tables</strong>.</p>
<section id="fact-tables-the-measurements" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="fact-tables-the-measurements"><span class="header-section-number">10.4.1</span> Fact Tables: The Measurements</h3>
<p>A fact table records the measurable events of a business process. Each row represents one discrete event at the lowest level of detail, what Kimball memorably called the “grain.” In a retail context, the grain might be the “beep” of the cash register scanner, one row per product scanned. In manufacturing, the grain might be one quality inspection, one sensor reading, or one production run.</p>
<p>The <code>order_details</code> table in Northwind is a fact table. Its grain is one line item within one order, and it contains measurements: <code>quantity</code>, <code>unit_price</code>, and <code>discount</code>. The foreign keys (<code>order_id</code>, <code>product_id</code>) connect each fact to its context.</p>
<p>Fact tables come in three common varieties. <strong>Transaction facts</strong> record discrete events (each sale, each inspection). <strong>Periodic snapshots</strong> summarize events over a standard period (daily inventory levels, weekly production totals). <strong>Accumulating snapshots</strong> track processes with milestones, like an order progressing through stages: ordered, released, shipped, delivered, with a date column for each milestone.</p>
<p>The measurements in fact tables also have important properties. <strong>Additive</strong> measures like revenue and quantity can be summed across all dimensions. <strong>Semi-additive</strong> measures like account balances can be summed across some dimensions but not others (you can sum balances across accounts, but not across time). <strong>Non-additive</strong> measures like ratios and percentages can’t be meaningfully summed at all, which is why experienced designers store the components separately and compute the ratio in the query.</p>
</section>
<section id="dimension-tables-the-context" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="dimension-tables-the-context"><span class="header-section-number">10.4.2</span> Dimension Tables: The Context</h3>
<p>Dimension tables provide the “who, what, where, when, why, and how” context for facts. They’re typically wide, flat tables with many text attributes that people use to filter and group data: product names and categories, customer names and regions, dates with year/quarter/month breakdowns.</p>
<p>The <code>products</code>, <code>customers</code>, <code>categories</code>, and <code>employees</code> tables in Northwind are all dimension tables. They provide the descriptive context that makes the numbers in <code>order_details</code> meaningful.</p>
<p>A well-designed dimension table uses verbose, human-readable descriptions rather than cryptic codes. Instead of storing <code>status_code = 3</code>, store <code>status_description = 'Shipped'</code>. This makes queries self-documenting and eliminates the need for lookup steps during analysis.</p>
</section>
<section id="star-schema" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="star-schema"><span class="header-section-number">10.4.3</span> Star Schema</h3>
<p>When you arrange a central fact table with dimension tables radiating outward, the structure looks like a star, hence the name <strong>star schema</strong>. This is the dominant design pattern in analytical databases and data warehouses.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>output</strong></pre>
</div>
<pre class="text" data-filename="output"><code>             ┌──────────┐
             │ products │
             └────┬─────┘
                  │
┌──────────┐     │     ┌────────────┐
│ customers├─────┼─────┤   dates    │
└──────────┘     │     └────────────┘
                  │
          ┌──────┴───────┐
          │ order_details │  ← fact table (center)
          │  (facts)      │
          └──────┬───────┘
                  │
┌──────────┐     │     ┌───────────┐
│ employees├─────┼─────┤ shippers  │
└──────────┘     │     └───────────┘
                  │
             ┌────┴─────┐
             │ suppliers │
             └──────────┘</code></pre>
</div>
<p>Star schemas are popular in analytics because they’re simple to understand (the design mirrors how business people think about data), they require few joins (usually just one hop from fact to dimension), and database engines are heavily optimized for this pattern.</p>
<p>Think of the fact table as a control panel showing measurements, and each dimension as a selector switch that filters what you see. Want to see sales by region? Join the region dimension. By product category? Join the product dimension. The star schema makes this kind of slicing and dicing natural.</p>
<p>A variation called the <strong>snowflake schema</strong> normalizes the dimension tables further, breaking hierarchies like <code>product → category → department</code> into separate tables. Kimball generally advises against snowflaking unless dimension tables are extremely large, because the added joins increase query complexity without significant benefit for most analytical workloads.</p>
<p>You don’t need to design star schemas while working through this book, but recognizing the pattern helps you navigate the analytical databases you’ll encounter in professional work. When you see a database with a large, narrow table full of numbers surrounded by wider tables full of descriptions, you’re looking at a dimensional model.</p>
</section>
<section id="exercises-2" class="level3" data-number="10.4.4">
<h3 data-number="10.4.4" class="anchored" data-anchor-id="exercises-2"><span class="header-section-number">10.4.4</span> Exercises</h3>
<ol type="1">
<li><p>Look at the <code>orders_flat</code> example from the normalization section. Identify a specific scenario where an update anomaly would occur (a change to one fact that requires modifying multiple rows). Then show how the normalized design prevents this problem.</p></li>
<li><p>In the Northwind database, identify which tables are fact tables and which are dimension tables. What is the grain of the <code>order_details</code> fact table? What is the grain of the <code>orders</code> table?</p></li>
<li><p>Consider a measure: “average unit price.” Is this additive, semi-additive, or non-additive? Why does this matter for how you store and compute it? What should you store in the fact table instead?</p></li>
<li><p>A data warehouse for a hospital stores patient visits as the fact table. Name four dimension tables that would provide useful context for analyzing patient visits, and list 2-3 example columns for each.</p></li>
<li><p>Draw (on paper or as text) a star schema for a university course registration system. The fact table records enrollments. What dimensions would surround it?</p></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> Update anomaly: changing Acme Corp’s address requires updating 3 rows. Miss one and the database disagrees with itself. Normalized: one UPDATE to the customers table fixes it everywhere.</p>
<p><strong>2.</strong> Fact tables: order_details (grain: one line item per order), orders (grain: one order). Dimension tables: products, customers, categories, employees, suppliers, shippers.</p>
<p><strong>3.</strong> Average unit price is non-additive,you can’t sum averages meaningfully. Store the additive components (total price, quantity) and compute the ratio at query time.</p>
<p><strong>4.</strong> Hospital dimensions: dim_patient (patientID, name, DOB, gender), dim_provider (providerID, name, specialty, department), dim_facility (facilityID, name, building, ward), dim_date (dateID, calendarDate, dayOfWeek, month).</p>
<p><strong>5.</strong> Fact table: enrollments (enrollmentID, studentID FK, courseID FK, semesterID FK, grade). Dimensions: students (studentID, name, major), courses (courseID, name, department, credits), semesters (semesterID, name, year, startDate).</p>
</div>
</div>
</div>
</section>
</section>
<section id="views-saved-queries" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="views-saved-queries"><span class="header-section-number">10.5</span> Views: Saved Queries</h2>
<p>A <strong>view</strong> is a saved query that behaves like a table. It doesn’t store data itself; every time you query a view, DuckDB runs the underlying query and returns the results. Views let you encapsulate complex logic behind a simple name.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Create a view that joins products with their categories and suppliers</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">VIEW</span> product_catalog <span class="kw">AS</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    p.product_id,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    p.product_name,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    c.category_name,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    s.company_name <span class="kw">AS</span> supplier,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    s.country <span class="kw">AS</span> supplier_country,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    p.unit_price,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    p.units_in_stock,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    p.discontinued</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> products <span class="kw">AS</span> p</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> categories <span class="kw">AS</span> c <span class="kw">ON</span> p.category_id <span class="op">=</span> c.category_id</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> suppliers <span class="kw">AS</span> s <span class="kw">ON</span> p.supplier_id <span class="op">=</span> s.supplier_id;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now anyone can write:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- This simple query hides the complexity of two joins</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    product_name,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    supplier,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    unit_price</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> product_catalog</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> supplier_country <span class="op">=</span> <span class="st">'Japan'</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> unit_price <span class="kw">DESC</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Views serve two purposes. For you, they save you from rewriting common joins and transformations. For others, they provide a simplified, curated interface to the data. A view named <code>monthly_sales_summary</code> is immediately understandable; the seven-join CTE that powers it is not.</p>
<p>To update or remove views:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Replace a view with a new definition</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">OR</span> <span class="kw">REPLACE</span> <span class="kw">VIEW</span> product_catalog <span class="kw">AS</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">..</span>.;  <span class="co">-- new query definition</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co">-- Remove a view entirely</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="kw">DROP</span> <span class="kw">VIEW</span> product_catalog;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="documenting-your-data-the-catalog-mindset" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="documenting-your-data-the-catalog-mindset"><span class="header-section-number">10.6</span> Documenting Your Data: The Catalog Mindset</h2>
<p>Creating tables and views is only half of database design. The other half is making sure people (including future you) can find and understand the data. In a professional setting, the question “where is the data I need, and what does it mean?” consumes an enormous amount of time. Research suggests employees spend roughly 1.8 hours per day searching for information, and the majority of enterprise data goes unanalyzed simply because people don’t know it exists.</p>
<p>The solution at scale is a <strong>data catalog</strong>, a system that inventories the data assets in an organization, their definitions, ownership, relationships, and usage patterns. Enterprise tools like DataHub, Alation, and Collibra provide sophisticated catalog capabilities, and teams using the dbt framework get lightweight documentation automatically generated from their code.</p>
<p>You won’t build an enterprise data catalog while working through this book, but the habits that catalogs formalize are worth developing now, because they scale to every level of work.</p>
<p>Even DuckDB’s UI demonstrates basic catalog principles. The left panel shows your databases, schemas, and tables. The <code>information_schema</code> views you learned in <a href="06-databases.html" class="quarto-xref"><span>Chapter 6</span></a> let you query this metadata programmatically:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- [STANDARD SQL] What tables exist in the database?</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> table_name</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> information_schema.<span class="kw">tables</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> table_schema <span class="op">=</span> <span class="st">'main'</span>;</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co">-- [STANDARD SQL] What columns does the products table have?</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> column_name, data_type, is_nullable</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> information_schema.<span class="kw">columns</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> table_name <span class="op">=</span> <span class="st">'products'</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>At the simplest level, a README file in your project repository that describes each table, its columns, and what the data represents is a “data catalog.” The practice of documenting your schema, including what each table contains, where the data comes from, how frequently it updates, and who owns it, is the same whether you’re working with a personal DuckDB file or a petabyte-scale data warehouse. Start the habit now.</p>
<p>Four types of metadata are worth tracking. <strong>Technical metadata</strong> covers the structural aspects: data types, column names, table sizes, constraints. <strong>Business metadata</strong> covers meaning: what does “revenue” mean in this context, who defines the KPI, what business rules apply. <strong>Operational metadata</strong> covers provenance: when was this table last updated, where did the data come from, what transformations were applied. <strong>Social metadata</strong> covers usage: which tables are queried most, who are the primary users, what questions does this data typically answer. You won’t track all four for a personal database, but being aware of these categories prepares you for professional data environments.</p>
</section>
<section id="manipulating-data-insert-update-delete" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="manipulating-data-insert-update-delete"><span class="header-section-number">10.7</span> Manipulating Data: INSERT, UPDATE, DELETE</h2>
<p>Creating tables defines the structure. <strong>Data Manipulation Language</strong> (DML) operations populate and maintain that structure.</p>
<section id="insert-adding-rows" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="insert-adding-rows"><span class="header-section-number">10.7.1</span> INSERT: Adding Rows</h3>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Insert a single row</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> production_lines (line_id, line_name, building, capacity)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="kw">VALUES</span> (<span class="dv">1</span>, <span class="st">'Assembly Line A'</span>, <span class="st">'Building 1'</span>, <span class="dv">500</span>);</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co">-- Insert multiple rows at once</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INSERT</span> <span class="kw">INTO</span> production_lines (line_id, line_name, building, capacity)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="kw">VALUES</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">2</span>, <span class="st">'Assembly Line B'</span>, <span class="st">'Building 1'</span>, <span class="dv">450</span>),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">3</span>, <span class="st">'Packaging Line 1'</span>, <span class="st">'Building 2'</span>, <span class="dv">800</span>),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">4</span>, <span class="st">'Packaging Line 2'</span>, <span class="st">'Building 2'</span>, <span class="dv">750</span>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The column list after the table name is technically optional if you provide values for every column in order, but always include it. It documents your intent and protects you from column-order surprises if someone modifies the table later.</p>
</section>
<section id="insert-from-a-query" class="level3" data-number="10.7.2">
<h3 data-number="10.7.2" class="anchored" data-anchor-id="insert-from-a-query"><span class="header-section-number">10.7.2</span> INSERT from a Query</h3>
<p>One of SQL’s most powerful patterns is creating data from queries:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Populate a summary table from raw data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> category_summary <span class="kw">AS</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    c.category_name,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> product_count,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fu">AVG</span>(p.unit_price), <span class="dv">2</span>) <span class="kw">AS</span> avg_price,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">SUM</span>(p.units_in_stock) <span class="kw">AS</span> total_stock</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> products <span class="kw">AS</span> p</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> categories <span class="kw">AS</span> c <span class="kw">ON</span> p.category_id <span class="op">=</span> c.category_id</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> c.category_name;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>CREATE TABLE ... AS SELECT</code> creates a new table and fills it with the query results in one step. This is how you materialize analytical results into persistent tables, a pattern you’ll use extensively when building data pipelines.</p>
</section>
<section id="update-modifying-existing-rows" class="level3" data-number="10.7.3">
<h3 data-number="10.7.3" class="anchored" data-anchor-id="update-modifying-existing-rows"><span class="header-section-number">10.7.3</span> UPDATE: Modifying Existing Rows</h3>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Increase capacity of a specific line</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="kw">UPDATE</span> production_lines</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SET</span> capacity <span class="op">=</span> <span class="dv">600</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> line_id <span class="op">=</span> <span class="dv">1</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Always include a <code>WHERE</code> clause with <code>UPDATE</code>. An <code>UPDATE</code> without <code>WHERE</code> modifies every row in the table, which is almost never what you intend.</p>
</section>
<section id="delete-removing-rows" class="level3" data-number="10.7.4">
<h3 data-number="10.7.4" class="anchored" data-anchor-id="delete-removing-rows"><span class="header-section-number">10.7.4</span> DELETE: Removing Rows</h3>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Remove a decommissioned line</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="kw">DELETE</span> <span class="kw">FROM</span> production_lines</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> line_id <span class="op">=</span> <span class="dv">4</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Like <code>UPDATE</code>, always use <code>WHERE</code> with <code>DELETE</code>. A bare <code>DELETE FROM production_lines</code> empties the entire table.</p>
<div class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>DML in Analytical Workflows
</div>
</div>
<div class="callout-body-container callout-body">
<p>As an analyst, you’ll use <code>INSERT</code> and <code>CREATE TABLE ... AS SELECT</code> frequently. You’ll use <code>UPDATE</code> and <code>DELETE</code> rarely. Analytical databases are designed for reading, not for frequent row-level modifications. When you need to “update” analytical data, the standard pattern is to rebuild the table from source data (using <code>CREATE OR REPLACE TABLE ... AS SELECT</code>) rather than modifying individual rows. This approach is simpler, auditable, and avoids the complications of tracking which rows changed and when.</p>
</div>
</div>
</section>
<section id="exercises-3" class="level3" data-number="10.7.5">
<h3 data-number="10.7.5" class="anchored" data-anchor-id="exercises-3"><span class="header-section-number">10.7.5</span> Exercises</h3>
<ol type="1">
<li><p>Create a view called <code>low_stock_alerts</code> that joins <code>products</code>, <code>categories</code>, and <code>suppliers</code> and shows only active (not discontinued) products where <code>units_in_stock</code> is at or below <code>reorder_level</code>. Include the product name, category name, supplier name, current stock, and reorder level. Then query your view with a simple <code>SELECT</code> to verify it works.</p></li>
<li><p>Write SQL to insert three rows into the <code>production_lines</code> table, then update the capacity of one line, then delete another. Verify the state of the table after each operation with a <code>SELECT</code>.</p></li>
<li><p>Run this query against Northwind:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> column_name, data_type, is_nullable</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> information_schema.<span class="kw">columns</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> table_name <span class="op">=</span> <span class="st">'products'</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> ordinal_position;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Compare the output to querying <code>information_schema.columns</code> with no filters. Why is <code>information_schema</code> more useful than ad-hoc inspection for data catalog automation?</p></li>
<li><p>Write a short README (3-5 sentences per table) documenting the manufacturing quality control schema from this chapter. For each table, state what it represents, its primary key, its key relationships, and any important constraints. This is the kind of documentation a teammate would need to start querying your data.</p></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">VIEW</span> low_stock_alerts <span class="kw">AS</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> p.product_name, c.category_name, s.company_name <span class="kw">AS</span> supplier,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    p.units_in_stock <span class="kw">AS</span> current_stock, p.reorder_level</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> products <span class="kw">AS</span> p</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> categories <span class="kw">AS</span> c <span class="kw">ON</span> p.category_id <span class="op">=</span> c.category_id</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> suppliers <span class="kw">AS</span> s <span class="kw">ON</span> p.supplier_id <span class="op">=</span> s.supplier_id</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> p.discontinued <span class="op">=</span> <span class="dv">0</span> <span class="kw">AND</span> p.units_in_stock <span class="op">&lt;=</span> p.reorder_level;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>2.</strong> INSERT three rows, UPDATE one capacity, DELETE one row, verify with SELECT after each step. (Straightforward DML practice,see the chapter examples for exact syntax.)</p>
<p><strong>3.</strong> <code>information_schema</code> is programmatic and queryable: you can filter columns by type, join with constraint metadata, and automate schema documentation across all tables at once.</p>
<p><strong>4.</strong> (Documentation exercise,write 3-5 sentences per table describing purpose, PK, relationships, and constraints for production_lines, operators, inspections, and defects.)</p>
</div>
</div>
</div>
</section>
</section>
<section id="working-with-real-world-data" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="working-with-real-world-data"><span class="header-section-number">10.8</span> Working with Real-World Data</h2>
<p>Everything in this chapter comes together when you move beyond Northwind’s clean, well-structured tables and encounter real data. The transition from classroom dataset to messy data is where database design skills prove their worth.</p>
<p>Real-world data has characteristics that the Northwind data doesn’t: inconsistent formatting, missing values, non-English text, duplicate records with subtle variations, and the kind of quality issues that no one warned you about. When you face this kind of data, the workflow is the same set of skills you’ve been building. You use <code>CREATE TABLE</code> to define a clean target schema, <code>INSERT ... SELECT</code> to load and transform data, joins to connect related entities, CTEs and window functions to build analytical queries, and views to present clean results. The challenge isn’t new syntax. It’s applying what you already know to a messier, more realistic context, where the right schema isn’t given to you. It’s your job to figure it out.</p>
<p>The SQL skills transfer directly. In Perkins’ language, you’ve been playing a junior version of the game with clean data and well-structured tables. Working with real data moves you closer to the full professional game. If you want practice with this transition, try downloading a public dataset from a source like Kaggle, the UCI Machine Learning Repository, or a government open data portal, and design a DuckDB database for it from scratch. You’ll discover that modeling decisions, like which columns deserve their own dimension table and which constraints to enforce, are where the real thinking happens.</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>You’ll Spend More Time Reading Schemas Than Writing Them
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter teaches you to design databases, but in your career you’ll spend ten times more effort understanding databases other people designed. The <code>information_schema</code> → data dictionary workflow you learned in <a href="06-databases.html" class="quarto-xref"><span>Chapter 6</span></a> is the most frequently used skill in professional data work. Every new project, every new client, every new job starts with “what data exists, what does it mean, and where does it come from?” The design skills in this chapter make you better at reading schemas too, because you’ll recognize the patterns (star schemas, junction tables, normalization levels) and understand the trade-offs the designer was making.</p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Looking Ahead: Connecting DuckDB to Python
</div>
</div>
<div class="callout-body-container callout-body">
<p>The databases you build with these skills become the analytical engine inside larger workflows. In the Integration module, you’ll connect DuckDB to Python and run queries programmatically. Here’s a preview of what that looks like:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>python</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23" data-filename="python"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> duckdb</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>con <span class="op">=</span> duckdb.<span class="ex">connect</span>(<span class="st">"northwind.duckdb"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> con.sql(<span class="st">"""</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT product_name, unit_price</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM products</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE unit_price &gt; 20</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY unit_price DESC</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>result.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The SQL is identical to what you’ve been writing in the DuckDB UI. The difference is that Python can take the results and do things with them: generate reports, feed them into visualizations, trigger alerts, or load them into other systems. Designing a clean, well-structured database now makes that automation dramatically simpler later.</p>
</div>
</div>
</section>
<section id="chapter-exercises" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="chapter-exercises"><span class="header-section-number">10.9</span> Chapter Exercises</h2>
<p>These exercises require you to apply the full modeling workflow: identifying entities, designing schemas, writing DDL, and thinking about how design decisions affect downstream analysis.</p>
<ol type="1">
<li><p><strong>Schema design from scratch.</strong> A small engineering consultancy tracks projects, clients, employees, and time entries. Each project belongs to one client, but a client can have many projects. Each employee can work on many projects, and each project can have many employees. Time entries record how many hours a specific employee worked on a specific project on a specific date. Design the schema: identify all tables, their columns and data types, primary keys, foreign keys, and any constraints. Write the <code>CREATE TABLE</code> statements.</p></li>
<li><p><strong>Normalize this.</strong> A colleague shows you their “master spreadsheet” for tracking equipment maintenance:</p>
<pre><code>| machine_name  | building | technician | tech_phone | repair_date | repair_type | parts_used | cost  |
| CNC Mill 4    | Bldg A   | Jane Smith | 555-0101   | 2024-01-15  | Preventive  | Belt, Oil  | 45.00 |
| CNC Mill 4    | Bldg A   | Jane Smith | 555-0101   | 2024-03-22  | Corrective  | Motor      | 320.00|
| Lathe 2       | Bldg B   | Bob Jones  | 555-0202   | 2024-02-10  | Preventive  | Oil        | 15.00 |</code></pre>
<p>Identify the redundancy, describe the anomalies that could occur, and design a normalized schema (at least three tables). Write the <code>CREATE TABLE</code> statements and explain how your design prevents each anomaly.</p></li>
<li><p><strong>Fact or dimension?</strong> For each table described below, state whether it’s a fact table or a dimension table and justify your answer: (a) A table of 50 million rows, each recording a single barcode scan at a warehouse with timestamp, product ID, warehouse ID, and quantity. (b) A table of 200 rows listing warehouse locations with name, address, region, manager name, and square footage. (c) A table of 5,000 rows containing product descriptions with name, category, brand, weight, and shelf life.</p></li>
<li><p><strong>View design.</strong> Create two views for the Northwind database that would be useful to different audiences. First, an <code>order_summary</code> view for a sales manager that shows each order with the customer name, order date, number of line items, and total order value (all pre-joined and pre-calculated). Second, a <code>supplier_catalog</code> view for a procurement manager that shows each supplier with the number of products they provide, average product price, and the categories they cover. Write the <code>CREATE VIEW</code> statements and test each with a simple query.</p></li>
<li><p><strong>End-to-end design exercise.</strong> A food truck business wants to track daily sales across three trucks that operate in different locations. They need to analyze sales by truck, location, day of week, menu item, and payment method. Design a star schema for this scenario. Identify the fact table and its grain, name all dimension tables with their columns, write the <code>CREATE TABLE</code> statements, insert at least 3 sample rows into each table, and write one analytical query that demonstrates the schema works (for example, “total revenue by truck by day of week”).</p></li>
<li><p><strong>Constraint enforcement test.</strong> DuckDB parses foreign key constraints but does not fully enforce them. Test this yourself: create a small <code>departments</code> table with a primary key, then create an <code>employees</code> table with a <code>FOREIGN KEY</code> referencing <code>departments</code>. Insert an employee with a <code>department_id</code> that doesn’t exist in the <code>departments</code> table. Does DuckDB accept or reject the row? Now explain why a production database like PostgreSQL <em>would</em> reject it, and describe the specific data quality problem that could occur if foreign keys aren’t enforced. What other practices (besides database constraints) can protect against this kind of error?</p></li>
<li><p><strong>Debug this schema.</strong> A colleague designed the following schema for tracking machine maintenance at a factory, but there are design problems. Identify at least four issues and explain how to fix each one.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>duckdb</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25" data-filename="duckdb"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> maintenance_log (</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    log_id <span class="dt">INTEGER</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    machine_name <span class="dt">VARCHAR</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    machine_building <span class="dt">VARCHAR</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    technician_name <span class="dt">VARCHAR</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    technician_phone <span class="dt">VARCHAR</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    repair_date <span class="dt">DATE</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    repair_type <span class="dt">VARCHAR</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    parts_used <span class="dt">VARCHAR</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">cost</span> <span class="dt">DECIMAL</span>(<span class="dv">10</span>, <span class="dv">2</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>(Hints: think about redundancy, constraints, normalization, and what happens when a technician changes their phone number.)</p></li>
<li><p><strong>View layering.</strong> Create a view called <code>product_summary</code> that joins <code>products</code>, <code>categories</code>, and <code>suppliers</code> to show each product with its category name, supplier name, unit price, and stock status (using a <code>CASE</code> expression). Then create a <em>second</em> view called <code>reorder_alert</code> that queries <code>product_summary</code> and filters to only products that need reordering. Write a query against <code>reorder_alert</code> and explain how layering views like this creates reusable building blocks for different audiences.</p></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> Tables: clients (client_id PK), projects (project_id PK, client_id FK), employees (employee_id PK), project_assignments (project_id FK, employee_id FK,junction table), time_entries (entry_id PK, project_id FK, employee_id FK, entry_date, hours).</p>
<p><strong>2.</strong> Normalize into: machines (machine_id, name, building), technicians (tech_id, name, phone), repairs (repair_id, machine_id FK, tech_id FK, repair_date, repair_type, parts_used, cost). Prevents update anomaly (phone stored once), delete anomaly (machines exist independently), and redundancy.</p>
<p><strong>3.</strong> (a) Fact table,50M discrete events with measurements. (b) Dimension,200 rows of descriptive warehouse attributes. (c) Dimension,5,000 rows of product descriptions.</p>
<p><strong>4.</strong> Views:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">VIEW</span> order_summary <span class="kw">AS</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> o.order_id, c.company_name, o.order_date, <span class="fu">COUNT</span>(od.product_id) <span class="kw">AS</span> line_items,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fu">SUM</span>(od.unit_price <span class="op">*</span> od.quantity), <span class="dv">2</span>) <span class="kw">AS</span> total_value</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> orders <span class="kw">AS</span> o</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> customers <span class="kw">AS</span> c <span class="kw">ON</span> o.customer_id <span class="op">=</span> c.customer_id</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> order_details <span class="kw">AS</span> od <span class="kw">ON</span> o.order_id <span class="op">=</span> od.order_id</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> o.order_id, c.company_name, o.order_date;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">VIEW</span> supplier_catalog <span class="kw">AS</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> s.company_name, <span class="fu">COUNT</span>(<span class="kw">DISTINCT</span> p.product_id) <span class="kw">AS</span> product_count,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ROUND</span>(<span class="fu">AVG</span>(p.unit_price), <span class="dv">2</span>) <span class="kw">AS</span> avg_price,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    STRING_AGG(<span class="kw">DISTINCT</span> c.category_name, <span class="st">', '</span>) <span class="kw">AS</span> categories</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> suppliers <span class="kw">AS</span> s</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> products <span class="kw">AS</span> p <span class="kw">ON</span> s.supplier_id <span class="op">=</span> p.supplier_id</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> categories <span class="kw">AS</span> c <span class="kw">ON</span> p.category_id <span class="op">=</span> c.category_id</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> s.supplier_id, s.company_name;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>5.</strong> Star schema: fact table = sales (sale_id, truck_id FK, location_id FK, date_id FK, item_id FK, payment_id FK, quantity, amount). Dimensions: trucks, locations, menu_items, payment_methods, dates. Write CREATE TABLE for each, insert sample data, then query total revenue by truck by day of week.</p>
<p><strong>6.</strong> DuckDB ACCEPTS the invalid foreign key (parses but doesn’t enforce). PostgreSQL would REJECT it, preventing orphaned records. Other protections: application-level validation, data quality audits, staging table checks.</p>
<p><strong>7.</strong> Issues: (a) no PRIMARY KEY on log_id, (b) redundancy,machine and technician info repeated across rows, (c) no NOT NULL or CHECK constraints on critical columns, (d) parts_used as comma-separated string loses structure. Fix: normalize into machines, technicians, and repairs tables with proper constraints.</p>
<p><strong>8.</strong> Create product_summary view (joins products+categories+suppliers, adds CASE for stock_status). Then create reorder_alert view that queries product_summary filtering for low/reorder stock. Layering lets you update join logic once and all dependent views benefit.</p>
</div>
</div>
</div>
</section>
<section id="summary" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="summary"><span class="header-section-number">10.10</span> Summary</h2>
<p>Database design begins by identifying entities (things you track) and relationships (how they connect), sketching these as entity-relationship diagrams before writing any SQL. Tools like dbdiagram.io let you define schemas in code (DBML) and generate visual diagrams with Crow’s foot notation that show relationship types at a glance. <code>CREATE TABLE</code> defines table structure with column names, data types, and constraints. Data types enforce what values a column can hold: <code>INTEGER</code> for whole numbers, <code>DECIMAL</code> for exact values like money, <code>VARCHAR</code> for text, <code>DATE</code> and <code>TIMESTAMP</code> for temporal data. Constraints enforce data quality rules: <code>PRIMARY KEY</code> ensures unique identification, <code>NOT NULL</code> prevents missing values, <code>FOREIGN KEY</code> maintains referential integrity between tables, <code>UNIQUE</code> prevents duplicates, and <code>CHECK</code> enforces custom conditions. Normalization organizes tables so each fact lives in one place, preventing update, insertion, and deletion anomalies. Analytical databases often use dimensional modeling instead, organizing data into star schemas with central fact tables (containing measurements from business events) surrounded by dimension tables (containing the descriptive “who, what, where, when” context). Views save complex queries behind simple names, serving as reusable building blocks and simplified interfaces for others. Documenting your data, through README files, metadata tracking, and consistent naming, is the small-scale version of the data catalog practices that professional organizations rely on. <code>INSERT</code>, <code>UPDATE</code>, and <code>DELETE</code> manipulate data within tables, with <code>CREATE TABLE ... AS SELECT</code> being the most common analytical pattern for materializing query results into persistent tables.</p>
</section>
<section id="glossary" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="glossary"><span class="header-section-number">10.11</span> Glossary</h2>
<dl>
<dt><strong>CHECK Constraint</strong></dt>
<dd>
A rule defined on a column that the database evaluates on every insert or update, rejecting values that violate the specified condition.
</dd>
<dt><strong>Constraint</strong></dt>
<dd>
A rule applied to a table or column that the database enforces automatically, ensuring data integrity by rejecting operations that would violate the rule.
</dd>
<dt><strong>CREATE TABLE</strong></dt>
<dd>
A SQL Data Definition Language (DDL) statement that defines a new table’s structure, including column names, data types, and constraints.
</dd>
<dt><strong>Crow’s Foot Notation</strong></dt>
<dd>
A visual convention used in entity-relationship diagrams where symbols at the ends of relationship lines indicate whether relationships are one-to-one, one-to-many, or many-to-many, and whether they are mandatory or optional.
</dd>
<dt><strong>Data Catalog</strong></dt>
<dd>
A system that inventories data assets in an organization, documenting their definitions, ownership, relationships, and usage patterns to help people find and understand available data.
</dd>
<dt><strong>Data Manipulation Language (DML)</strong></dt>
<dd>
The subset of SQL used to add, modify, and remove data within tables: <code>INSERT</code>, <code>UPDATE</code>, and <code>DELETE</code>.
</dd>
<dt><strong>DBML (Database Markup Language)</strong></dt>
<dd>
A code-based language used by dbdiagram.io to define database schemas, with syntax for tables, columns, constraints, and relationships that generates visual ER diagrams.
</dd>
<dt><strong>Denormalization</strong></dt>
<dd>
The deliberate introduction of redundancy into a database schema, typically in analytical tables, to reduce the number of joins needed for frequent queries.
</dd>
<dt><strong>Dimension Table</strong></dt>
<dd>
A table in a dimensional model that provides descriptive context (the “who, what, where, when”) for filtering and grouping facts. Typically wide, flat, and text-heavy.
</dd>
<dt><strong>Dimensional Modeling</strong></dt>
<dd>
A database design approach for analytical systems that organizes data into fact tables (measurements) and dimension tables (context), following star or snowflake schema patterns. Pioneered by Ralph Kimball.
</dd>
<dt><strong>Entity-Relationship Diagram (ERD)</strong></dt>
<dd>
A visual representation of the entities (tables), attributes (columns), and relationships (foreign keys) in a database schema.
</dd>
<dt><strong>Fact Table</strong></dt>
<dd>
A table in a dimensional model that records measurable events from a business process. Each row represents one event at the declared grain, and columns contain measurements (quantities, amounts) and foreign keys to dimension tables.
</dd>
<dt><strong>Foreign Key Constraint</strong></dt>
<dd>
A rule that ensures a column’s value references an existing value in another table’s primary key column, preventing orphaned records.
</dd>
<dt><strong>Grain</strong></dt>
<dd>
In dimensional modeling, the level of detail that each row in a fact table represents. Declaring the grain (e.g., “one row per line item per order”) is the first and most important step in designing a fact table.
</dd>
<dt><strong>Normalization</strong></dt>
<dd>
The process of organizing a relational database to minimize redundancy and prevent data anomalies, following a series of progressively stricter “normal forms.”
</dd>
<dt><strong>NOT NULL Constraint</strong></dt>
<dd>
A rule that prevents a column from containing <code>NULL</code> values, requiring that every row has a defined value for that column.
</dd>
<dt><strong>Referential Integrity</strong></dt>
<dd>
The guarantee that every foreign key value in a table corresponds to an existing primary key value in the referenced table, maintaining valid relationships between entities.
</dd>
<dt><strong>Star Schema</strong></dt>
<dd>
A database design pattern used in analytical databases where a central fact table (containing measurements and metrics) connects to surrounding dimension tables (containing descriptive attributes). Named for its star-like visual appearance.
</dd>
<dt><strong>View</strong></dt>
<dd>
A saved SQL query that behaves like a virtual table. Views don’t store data; they execute the underlying query each time they’re accessed, providing a simplified or curated interface to the data.
</dd>
</dl>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ozanozbeker\.com\/cw4e\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/09-analytics.html" class="pagination-link" aria-label="Analytical SQL">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analytical SQL</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../programming.html" class="pagination-link" aria-label="Programming">
        <span class="nav-page-text">Programming</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Ozan Ozbeker | CC-BY-NC-ND 4.0</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ozanozbeker/cw4e/edit/main/chapters/10-modeling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ozanozbeker/cw4e/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>